export const homePageStyles = {
  navbar: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    width: 'calc(100vw - 16px)',
    zIndex: 100,
    background: 'white',
    boxSizing: 'border-box' as const,
  },
  snapContainer: {
    height: '100vh',
    width: '100vw',
    overflowY: 'scroll' as const,
    overflowX: 'hidden' as const,
    scrollSnapType: 'y mandatory' as const,
    scrollBehavior: 'smooth' as const,
    boxSizing: 'border-box' as const,
  },
  section: {
    minHeight: '100vh',
    width: '100vw',
    scrollSnapAlign: 'start' as const,
    display: 'flex',
    flexDirection: 'column' as const,
    justifyContent: 'center',
    alignItems: 'stretch',
    position: 'relative' as const,
    boxSizing: 'border-box' as const,
  },
  bg: {
    minHeight: '100vh',
    minWidth: '100vw',
    background: 'linear-gradient(to bottom, #f7f7fa 0%, #e9dede 100%)',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'stretch',
    fontFamily: 'Reddit Sans, Arial, sans-serif',
    paddingTop: 70, // adjust for navbar height
    boxSizing: 'border-box' as const,
  },
  content: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    minHeight: 0,
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  content60: {
    width: '60vw',
    marginLeft: '20vw',
    marginRight: '20vw',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'flex-start',
    boxSizing: 'border-box' as const,
  },
} as const; 